AWSTemplateFormatVersion: '2010-09-09'
Description: Build and push LiteLLM Docker image to ECR using CodeBuild (manual builds only)

Parameters:
  RepositoryName:
    Type: String
    Default: litellm
    Description: ECR repository name
  ImageTag:
    Type: String
    Default: latest
    Description: Image tag to push
  GitHubRepoUrl:
    Type: String
    Default: https://github.com/BerriAI/litellm.git
    Description: LiteLLM GitHub repository URL
  CodeBuildComputeType:
    Type: String
    Default: BUILD_GENERAL1_MEDIUM
    AllowedValues:
      - BUILD_GENERAL1_SMALL
      - BUILD_GENERAL1_MEDIUM
      - BUILD_GENERAL1_LARGE
    Description: CodeBuild instance size

Resources:
  EcrRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Ref RepositoryName

  CodeBuildServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
            Action: sts:AssumeRole
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/CloudWatchLogsFullAccess
      Policies:
        - PolicyName: CodeBuildEcrAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - ecr:GetAuthorizationToken
                Resource: '*'
              - Effect: Allow
                Action:
                  - ecr:BatchCheckLayerAvailability
                  - ecr:CompleteLayerUpload
                  - ecr:GetDownloadUrlForLayer
                  - ecr:InitiateLayerUpload
                  - ecr:PutImage
                  - ecr:UploadLayerPart
                  - ecr:DescribeRepositories
                  - ecr:BatchGetImage
                Resource: !GetAtt EcrRepository.Arn
              - Effect: Allow
                Action:
                  - ssm:GetParameter
                  - ssm:GetParameters
                  - ssm:GetParameterHistory
                Resource: '*'
                Condition:
                  StringLike:
                    'ssm:Name': 
                      - '/aws/service/*'
                      - '/litellm/*'
              - Effect: Allow
                Action:
                  - ec2:DescribeRegions
                Resource: '*'

  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub ${AWS::StackName}-litellm-build
      ServiceRole: !GetAtt CodeBuildServiceRole.Arn
      Artifacts:
        Type: NO_ARTIFACTS
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: !Ref CodeBuildComputeType
        Image: aws/codebuild/standard:7.0
        PrivilegedMode: true
        EnvironmentVariables:
          - Name: REPOSITORY_NAME
            Value: !Ref RepositoryName
          - Name: IMAGE_TAG
            Value: !Ref ImageTag
      Source:
        Type: GITHUB
        Location: !Ref GitHubRepoUrl
        GitCloneDepth: 1
        BuildSpec: |
          version: 0.2
          env:
            shell: bash
          phases:
            pre_build:
              commands:
                - echo Logging in to Amazon ECR...
                - ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
                - REGION=$AWS_DEFAULT_REGION
                - REPOSITORY_URI=$ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/$REPOSITORY_NAME
                - aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com
            build:
              commands:
                - echo Building LiteLLM Docker image with AWS tools...
                - ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
                - REGION=$AWS_DEFAULT_REGION
                - REPOSITORY_URI=$ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/$REPOSITORY_NAME
                - SHORT_SHA=${CODEBUILD_RESOLVED_SOURCE_VERSION:0:7}
                - |
                  cat > Dockerfile.aws-enhanced <<'EOF'
                  # Start directly from the official LiteLLM image and just add AWS tools
                  FROM ghcr.io/berriai/litellm:main-latest
                  
                  # Switch to root to install packages
                  USER root
                  
                  # Install AWS utilities on top of the existing image
                  RUN apt-get update && \
                      apt-get install -y \
                          curl \
                          unzip \
                          tar \
                          gzip \
                          wget \
                          && \
                      # Install AWS CLI v2
                      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" && \
                      unzip awscliv2.zip && \
                      ./aws/install && \
                      rm -rf awscliv2.zip aws && \
                      # Install SSM Agent (if needed for ECS tasks)
                      wget https://s3.amazonaws.com/ec2-downloads-windows/SSMAgent/latest/debian_amd64/amazon-ssm-agent.deb && \
                      dpkg -i amazon-ssm-agent.deb || apt-get install -f -y && \
                      rm amazon-ssm-agent.deb && \
                      # Clean up
                      apt-get clean && \
                      rm -rf /var/lib/apt/lists/*
                  
                  # Create non-root user for security (if it doesn't exist)
                  RUN id -u litellm >/dev/null 2>&1 || useradd -m -u 1000 litellm
                  
                  # Switch back to non-root user
                  USER litellm
                  
                  # Health check
                  HEALTHCHECK --interval=30s --timeout=10s --start-period=5s --retries=3 \
                      CMD curl -f http://localhost:4000/health || exit 1
                  
                  # Keep the original working directory and command from the base image
                  # The base image already has the correct setup
                  EOF
                - docker build -t "$REPOSITORY_NAME:$IMAGE_TAG" -t "$REPOSITORY_URI:$IMAGE_TAG" -t "$REPOSITORY_URI:sha-$SHORT_SHA" -f Dockerfile.aws-enhanced .
            post_build:
              commands:
                - echo Pushing image to ECR...
                - ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
                - REGION=$AWS_DEFAULT_REGION
                - REPOSITORY_URI=$ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/$REPOSITORY_NAME
                - docker push "$REPOSITORY_URI:$IMAGE_TAG"
                - docker push "$REPOSITORY_URI:sha-$SHORT_SHA"
                - echo Build completed on `date`
      TimeoutInMinutes: 60
      QueuedTimeoutInMinutes: 60

Outputs:
  EcrRepositoryUri:
    Description: ECR repository URI
    Value: !Sub ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${RepositoryName}
  EcrRepositoryName:
    Description: ECR repository name
    Value: !Ref EcrRepository
  CodeBuildProjectName:
    Description: CodeBuild project name to trigger manual builds
    Value: !Ref CodeBuildProject
  CodeBuildProjectArn:
    Description: CodeBuild project ARN
    Value: !GetAtt CodeBuildProject.Arn
  StartBuildCommand:
    Description: CLI command to start a manual build
    Value: !Sub aws codebuild start-build --project-name ${CodeBuildProject}

